version: '2'

networks:
    basic-network-extension_caldera:
      external: true

services:
  peer0.owner-org:
    container_name: peer0.owner-org
    image: org3-peer
    environment:
      - CORE_PEER_ID=peer0.owner-org
      - CORE_PEER_ADDRESS=peer0.owner-org:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.owner-org:7051
      - CORE_PEER_LOCALMSPID=OwnerOrgMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=basic-network-extension_caldera
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_MSPCONFIGPATH=/peer/crypto/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/peer/crypto/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/peer/crypto/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/peer/crypto/tls/ca.crt
    ports:
      - 19051:7051
      - 19053:7053
    networks:
      - basic-network-extension_caldera
    working_dir: /peer
    command: peer node start
    volumes:
      - /var/run:/host/var/run/


  org3-ca:
    container_name: org3-ca
    extends:
      file: ../ca-base.yaml
      service: ca-base
    image: org3-ca
    ports:
      - 13054:7054
    networks:
      - basic-network-extension_caldera

  org3cli:
    container_name: org3cli
    stdin_open: true
    tty: true
    image: org3cli
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - GOPATH=/opt/gopath
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=org3cli
      - CORE_PEER_ADDRESS=peer0.owner-org:7051
      - CORE_PEER_LOCALMSPID=OwnerOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/peers/peerOrganizations/owner-org/peers/peer0.owner-org/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/peers/peerOrganizations/owner-org/peers/peer0.owner-org/tlse/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/peers/peerOrganizations/owner-org/peers/peer0.owner-org/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/peers/peerOrganizations/owner-org/users/Admin@owner-org/msp
    depends_on:
      - peer0.owner-org
    volumes:
       - ../containers/api/chaincode/src:/opt/gopath/src
    networks:
      - basic-network-extension_caldera

  # api-org3:
  #   container_name: api-org3
  #   image: api-org3
  #   environment:
  #     - PORT=4000
  #     - DOCKER_SOCKET_PATH=/host/var/run/docker.sock
  #     - DOCKER_CCENV_IMAGE=hyperledger/fabric-ccenv:x86_64-1.1.0
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - /var/run/:/host/var/run/
  #   depends_on:
  #     - peer0.owner-org
  #   networks:
  #     - basic-network-extension_caldera
