version: '2'

networks:
    basic-network-extension_caldera:
      external: true

services:
  api-org3:
    container_name: api-org3
    image: api-org3
    environment:
      - PORT=4000
      - DOCKER_SOCKET_PATH=/host/var/run/docker.sock
      - DOCKER_CCENV_IMAGE=hyperledger/fabric-ccenv:x86_64-1.1.0
    ports:
      - 4000:4000
    volumes:
      - /var/run/:/host/var/run/
    networks:
      - basic-network-extension_caldera
