version: '2'

services:
  peer-base:
    image: hyperledger/fabric-peer:x86_64-1.1.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=basic-network-kafka_caldera
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_TLS_CERT_FILE=/peer/crypto/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/peer/crypto/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/peer/crypto/tls/ca.crt
    working_dir: /peer
    command: peer node start
    volumes:
      - /var/run:/host/var/run/
