# crypto-config.yaml specifies a configuration for the cryptogen binary.
# this binary outputs cryptographic material nessissary to specify a fabric network
# Here we define our networks initial organizations.
# Organizations are the backbone of delegating network permissions

# OrdererOrgs contains specification for Orderer Organizations
# These organizations permission operation of the orderer nodes
OrdererOrgs:
  # Domain and spec keys specify network mapping
  - Name: OrdererOrg
    Domain: orderer-org
    Specs:
      - Hostname: orderer0

# PeerOrgs contains specification for the Peer Organizations
# These Organizations permission operation of various peer nodes
PeerOrgs:
  - Name: ArtistOrg
    Domain: artist-org
    # multiple hostnames under one org configures multiple peers to one org
    Specs:
      - Hostname: artist-peer-florence
      - Hostname: artist-peer-paris

  - Name: BrokerOrg
    Domain: broker-org
    Specs:
      - Hostname: broker-peer-florence
      - Hostname: broker-peer-paris


