version: '2'

networks:
  net_caldera:
    external: true

services:
    b9-ca-api:
      container_name: b9-ca-api
      image: b9-ca-api
      environment:
        - PORT=3000
        - DOCKER_SOCKET_PATH=/host/var/run/docker.sock
        - DOCKER_CCENV_IMAGE=hyperledger/fabric-ccenv:x86_64-1.1.0
      ports:
        - 3000:3000
      volumes:
        - /var/run/:/host/var/run/
      networks:
        - net_caldera

